language : android
jdk: oraclejdk8
# ...

# Global Reference Values for the file
env:
  global:
  #Android API Version for the code
   - ANDROID_API_LEVEL=28

   
  #Android API Version for the emulator 
   - EMULATOR_API_LEVEL=22
   
  #Android Build Tools Version
   - ANDROID_BUILD_TOOLS_VERSION=28.0.0
   
  #Install Timeout (by default 2min is not enough for slow computers)
   - ADB_INSTALL_TIMEOUT=20
   - ANDROID_ABI=armeabi-v7a 

   #... 


   
android:
  components:
  
    - build-tools-$ANDROID_BUILD_TOOLS_VERSION
    - android-$EMULATOR_API_LEVEL
    - sys-img-armeabi-v7a-android-$EMULATOR_API_LEVEL






before_install:
 
 - yes | sdkmanager "platforms;android-28"


before_script:
  - chmod +x gradlew




after_success:
  - bash <(curl -s https://codecov.io/bash)