language : android
jdk: oraclejdk8
# ...

# Global Reference Values for the file
env:
  global:
  #Android API Version for the code
   - ANDROID_API_LEVEL=28

   
  #Android API Version for the emulator 
   - EMULATOR_API_LEVEL=22
   
  #Android Build Tools Version
   - ANDROID_BUILD_TOOLS_VERSION=28.0.2
   
  #Install Timeout (by default 2min is not enough for slow computers)
   - ADB_INSTALL_TIMEOUT=20 
   - ANDROID-ABI=armeabi-v7a
   - ANDROID_TAG=google_apis

   #... 


   
android:
 components:
 
    # Android SDK Tools
    - tools
    - platform-tools
    
    #repeat tools to get newer Android SDK Tools
    - tools 
    
    # The SDK version used to compile your project
    - android-$ANDROID_API_LEVEL
    
     # The SDK version used by emulator
    - android-$EMULATOR_API_LEVEL
    
     # The BuildTools version used by your project
    - build-tools-$ANDROID_BUILD_TOOLS_VERSION
    
    # Specify at least one system image for emulator
    - sys-img-$ANDROID_ABI-google_apis-$ANDROID_EMULATOR_LEVEL
    
    # Additional components
    - extra-android-m2repository
    - extra-google-m2repository
    - extrat-android-support


    #...
 # ... 


before_install:
 - chmod +x gradlew

# ...
script: 
 ./gradlew connectedAndroidTest